# 01 - Disparo Manual

# Nome da pipeline
name: 'N1 - Execução Manual'

# Gatilho manual
on:
  workflow_dispatch:

jobs:
  test-gerenciarPagamento:
    # Máquina onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Clonar o projeto
      - name: Checkout do projeto
        uses: actions/checkout@v5

      # Instalar o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      # Instalar as dependências do projeto
      - name: Instalar dependências
        run: npm ci

      - name: Instalar Mocha e Mochawesome
        run: npm install mocha@11.7.6 mochawesome@7.1.4

      # Executar os testes
      - name: Executar testes de gerenciarPagamento
        run: npx mocha --reporter mochawesome

      # Gerar o relatorio do resultado
      - name: Gerar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resultado-gerenciarPagamento
          path: mochawesome-report/